<?php
 // module/Timeline/view/timeline/timeline/add.phtml:

 $title = 'Add new timeline';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('timeline', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('startdate'));
 echo $this->formRow($form->get('enddate'));
 echo $this->formRow($form->get('headline'));
 echo $this->formRow($form->get('text'));
 echo $this->formRow($form->get('media'));
 echo $this->formRow($form->get('mediacredit'));
 echo $this->formRow($form->get('mediacaption'));
 echo $this->formRow($form->get('mediathumbnail'));
 echo $this->formRow($form->get('type'));
 echo $this->formRow($form->get('tag'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();