<?php
 // module/Timeline/view/timeline/timeline/delete.phtml:

 $title = 'Delete timeline';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($timeline->title); ?>' by
     '<?php echo $this->escapeHtml($timeline->artist); ?>'?
 </p>
 <?php
 $url = $this->url('timeline', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $timeline->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>
