<?php
 // module/Timeline/view/timeline/timeline/edit.phtml:

 $title = 'Edit timeline';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'timeline',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('startdate'));
 echo $this->formRow($form->get('enddate'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
